/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Matematicas.*;

/**
 *
 * @author alvar
 */
public class entrada extends javax.swing.JFrame {

    /**
     * Creates new form Interfase
     */
    public entrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbtnRR = new javax.swing.JRadioButton();
        rbtnSJF = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEjecucion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtLlegada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnSimular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sistema simulador de planificación de procesos");

        jLabel2.setText("Tipo de proceso: ");

        buttonGroup4.add(rbtnRR);
        rbtnRR.setText("Round Robin");
        rbtnRR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRRActionPerformed(evt);
            }
        });

        buttonGroup4.add(rbtnSJF);
        rbtnSJF.setText("Shortest Job First");
        rbtnSJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSJFActionPerformed(evt);
            }
        });

        jLabel3.setText("Procesos:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Tiempo de ejecucion:");

        txtEjecucion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEjecucionKeyTyped(evt);
            }
        });

        jLabel6.setText("Tiempo de llegada:");

        txtLlegada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLlegadaKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Tiempo de ejecución", "Tiempo de llegada"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnSimular.setText("Simular");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Tiempo de ejecución", "Tiempo de llegada", "Tiempo de comienzo", "Tiempo de finalización"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnSJF)
                                            .addComponent(rbtnRR)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnAgregar)
                                .addGap(289, 289, 289)
                                .addComponent(btnSimular)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnRR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnSJF)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimular)
                    .addComponent(btnSalir)
                    .addComponent(btnAgregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnRRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnRRActionPerformed

    private void rbtnSJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSJFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSJFActionPerformed

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        // Pasar data a clase y a la tabla
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        String name;
        int execution;
        int arrival;
        Proceso pro;
        //salida sal = new salida();
        if (rbtnRR.isSelected() == true) {      
            if (tblModel.getRowCount()== 0) {
                JOptionPane.showMessageDialog(this, "Agrege almenos un proceso");
            }else{
                System.out.println("Inicio de la simulación:");
                int quantum = 20;
                Matematicas.ColaEnlazada cola = new Matematicas.ColaEnlazada();
                for (int i = 0; i < tblModel.getRowCount(); i++) {
                    name = tblModel.getValueAt(i, 0).toString();
                    execution = Integer.valueOf(tblModel.getValueAt(i, 1).toString());
                    arrival = Integer.valueOf(tblModel.getValueAt(i, 2).toString());
                    pro = new Matematicas.Proceso(name, arrival, execution);
                    cola.encolar(pro);
                }
                Matematicas.RoundRobin roundRobin = new Matematicas.RoundRobin(cola, quantum);
                roundRobin.ejecutarRoundRobin();
                //sal = new salida(cola, len);
                
                DefaultTableModel tblModel2 = (DefaultTableModel)jTable2.getModel();
                for (int i = 0; i < tblModel.getRowCount(); i++) {
                    //pro = cola.desencolar();
                    //String te = String.valueOf(pro.getTiempoEjecucion());
                    //String tl = String.valueOf(pro.getTiempoLlegada());
                    //String tc = String.valueOf(pro.getTiempoComienzo());
                    //String tf = String.valueOf(pro.getTiempoFinalizacion());
                    String name2 = tblModel.getValueAt(i, 0).toString();
                    String execution2 = tblModel.getValueAt(i, 1).toString();
                    String arrival2 = tblModel.getValueAt(i, 2).toString();
                    //arrival = tblModel.getValueAt(i, 2).toString();
                    String data[] = {name2, execution2, arrival2, "", ""};
                    tblModel2.addRow(data);
                }
            }
        }else if(rbtnSJF.isSelected() == true){
            
            if (tblModel.getRowCount()== 0) {
                JOptionPane.showMessageDialog(this, "Agrege almenos un proceso");
            }else{
                System.out.println("Inicio de la simulación:");
                Matematicas.Proceso[] prog = new Proceso[tblModel.getRowCount()];
                Matematicas.SJR sjr = new Matematicas.SJR();
                DefaultTableModel tblModel2 = (DefaultTableModel)jTable2.getModel();
                for (int i = 0; i < tblModel.getRowCount(); i++) {
                    name = tblModel.getValueAt(i, 0).toString();
                    execution = Integer.valueOf(tblModel.getValueAt(i, 1).toString());
                    arrival = Integer.valueOf(tblModel.getValueAt(i, 2).toString());
                    prog[i] = new Proceso(name, arrival, execution);
                    
                    String name2 = tblModel.getValueAt(i, 0).toString();
                    String execution2 = tblModel.getValueAt(i, 1).toString();
                    String arrival2 = tblModel.getValueAt(i, 2).toString();
                    String data[] = {name2, execution2, arrival2, "", ""};
                    tblModel2.addRow(data);
                }
                sjr.ejecutarSJR(prog);
                //sal = new salida();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un tipo de simulacion");
        }
        //sal.show();
        //dispose();
    }//GEN-LAST:event_btnSimularActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Agrega los procesos a la lista:
        if (txtNombre.getText().equals("")||txtEjecucion.getText().equals("")||txtLlegada.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Llenar todo los datos es requerido");
        }else{
            String data[] = {txtNombre.getText(),txtEjecucion.getText(),txtLlegada.getText()};
            
            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
            tblModel.addRow(data);
            
            txtNombre.setText("");
            txtEjecucion.setText("");
            txtLlegada.setText("");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtEjecucionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEjecucionKeyTyped
        // Solo numeros:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEjecucionKeyTyped

    private void txtLlegadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLlegadaKeyTyped
        // Solo numeros:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtLlegadaKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSimular;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton rbtnRR;
    private javax.swing.JRadioButton rbtnSJF;
    private javax.swing.JTextField txtEjecucion;
    private javax.swing.JTextField txtLlegada;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
